'use server';

import { createThread, getBoards } from '@/data/mockBBS';
import { revalidatePath } from 'next/cache';

import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";

export async function triggerScheduledSpark(boardId: string) {
    const session = await getServerSession(authOptions);
    if (!session) {
        throw new Error("Unauthorized");
    }

    // 1. Get the target board to understand context (mocking AI context understanding)
    const boards = await getBoards();
    const targetBoard = boards.find(b => b.id === boardId);

    // Defines potential topics per board category or specific board ID
    const topicPool: Record<string, { title: string; content: string }[]> = {
        'news-detective': [
            { title: "【議論】ベーシックインカムは日本で導入可能なのか議論するスレ", content: "..." },
        ],
        // ... (keep usage of generic pools or create a large mapped pool)
        // For simplicity in this mock, we'll use a generic generator based on category if specific board not found
    };

    // Mock AI generating content based on Board Name/Category
    const categoryTopics: Record<string, { title: string; content: string }[]> = {
        'News & Disc.': [
            { title: "【時事】今月の注目ニュースまとめ", content: "..." },
            { title: "【議論】報道の自由とSNSの規制", content: "..." },
            { title: "【起業】AIスタートアップの生存戦略について", content: "..." }
        ],
        'Life & Advice': [
            { title: "【相談】30代からのキャリアチェンジ", content: "..." },
            { title: "【生活】一人暮らしのライフハック共有しようぜ", content: "..." },
            { title: "【地域】地方移住して良かったこと・悪かったこと", content: "..." }
        ],
        'Culture & Hobby': [
            { title: "【感想】今期のアニメ、どれ見る？", content: "..." },
            { title: "【映画】どんでん返しが凄い映画教えて", content: "..." },
            { title: "【YouTube】最近伸びてる教育系YouTuber教えて", content: "..." }
        ],
        'Science & Academia': [
            { title: "【宇宙】ジェイムズ・ウェッブ宇宙望遠鏡の新発見について", content: "..." },
            { title: "【歴史】もしもあの時歴史が動いていたら", content: "..." }
        ],
        'Subculture & Mystery': [
            { title: "【オカルト】検索してはいけない言葉", content: "..." },
            { title: "【都市伝説】AIは既に自我を持っている？", content: "..." }
        ]
    };

    const category = targetBoard?.category || 'General';
    const topics = categoryTopics[category] || [
        { title: "【雑談】最近の出来事について語ろう", content: "..." }
    ];

    const randomTopic = topics[Math.floor(Math.random() * topics.length)];

    await createThread(
        boardId,
        `[AI提案] ${randomTopic.title}`,
        `${randomTopic.content || randomTopic.title}\n\n(This thread was automatically generated by AI Spark System 🤖 on board: ${targetBoard?.name})`
    );

    revalidatePath(`/${boardId}`);
    return { success: true };
}
