'use client';

import { useState, useEffect } from 'react';
import styles from './ThreadSummarizer.module.css';

// Auto-summarize thresholds
const SUMMARY_THRESHOLDS = [20, 50, 100, 200, 500];

interface ThreadSummarizerProps {
    threadId: string;
    initialSummary?: string;
    postCount: number;
}

export default function ThreadSummarizer({ threadId, initialSummary, postCount }: ThreadSummarizerProps) {
    const [summary, setSummary] = useState<string | null>(initialSummary || null);
    const [isLoading, setIsLoading] = useState(false);
    const [isOpen, setIsOpen] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Auto-trigger summarization when postCount hits a threshold
    useEffect(() => {
        if (postCount < 20) return; // Don't summarize below 20

        const shouldAutoSummarize = SUMMARY_THRESHOLDS.some(threshold =>
            postCount >= threshold && postCount < threshold + 5 // Within 5 posts of threshold
        );

        if (shouldAutoSummarize && !summary && !isLoading) {
            handleSummarize();
        }
    }, [postCount]);

    const handleSummarize = async () => {
        setIsLoading(true);
        setError(null);

        try {
            const res = await fetch('/api/thread/summarize', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ threadId }),
            });

            if (!res.ok) {
                const data = await res.json();
                throw new Error(data.error || 'Failed to summarize');
            }

            const data = await res.json();
            setSummary(data.summary);
            setIsOpen(true);
        } catch (err: any) {
            console.error('Summarization error:', err);
            setError(err.message || '要約の生成に失敗しました');
        } finally {
            setIsLoading(false);
        }
    };

    // Don't render at all if less than 20 posts
    if (postCount < 20) {
        return null;
    }

    return (
        <div className={styles.container}>
            <div className={styles.header}>
                <h3 className={styles.title}>NWWW要約 (3-Line Summary)</h3>
                <span className={styles.postCountBadge}>{postCount}レス</span>
            </div>

            {/* Error State */}
            {error && (
                <div className={styles.action}>
                    <p className={styles.errorText}>{error}</p>
                    <button onClick={handleSummarize} className={styles.button}>
                        再試行
                    </button>
                </div>
            )}

            {/* No summary yet — offer to generate */}
            {!summary && !isLoading && !error && (
                <div className={styles.action}>
                    <p className={styles.description}>
                        {postCount}件のレスがあります。<br />
                        NWWWで議論の要点を3行に要約します。
                    </p>
                    <button onClick={handleSummarize} className={styles.button}>
                        要約を生成する
                    </button>
                </div>
            )}

            {/* Summary exists but collapsed */}
            {summary && !isOpen && !isLoading && (
                <div className={styles.action}>
                    <p className={styles.description}>
                        NWWWによる3行要約が生成されています。
                    </p>
                    <button onClick={() => setIsOpen(true)} className={styles.button}>
                        要約を表示する
                    </button>
                </div>
            )}

            {/* Loading */}
            {isLoading && (
                <div className={styles.loading}>
                    <div className={styles.spinner}></div>
                    <p>NWWWがスレッドを分析中...</p>
                </div>
            )}

            {/* Summary open */}
            {summary && isOpen && (
                <div className={styles.result}>
                    <ul className={styles.summaryList}>
                        {summary.split('\n').filter(line => line.trim()).map((line, index) => (
                            <li key={index} className={styles.summaryItem}>{line}</li>
                        ))}
                    </ul>
                    <div className={styles.meta}>
                        Generated by NWWW AI • {postCount}レス時点
                    </div>
                    <div className={styles.actions}>
                        <button onClick={handleSummarize} className={styles.refreshButton} disabled={isLoading}>
                            🔄 最新の要約に更新
                        </button>
                        <button onClick={() => setIsOpen(false)} className={styles.closeButton}>
                            閉じる
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
